#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-y  += cst0xx_ts.o
#cst0xx_ts-objs += cst0xx.o cst0xx_ctl.o cst0xx_ex_fun.o
cst0xx_ts-objs := cst0xx.o
cst0xx_ts-objs += cst0xx_ctl.o
cst0xx_ts-objs += cst0xx_ex_fun.o
#cst0xx_ts-y    += cst0xx.o cst0xx_ctl.o cst0xx_ex_fun.o
